### PR TITLE
Support Team in Short Create

### PR DESCRIPTION
**Pull request by omairvaiyani**
Currently you cannot set the Team when creating a Shortcut Story. This adds a new flag `-T, --team`.

### CODE REVIEW

**Comment by panozzaj** [comment]
Not an expert with this package, but seems like a good change to me!

**Comment by j-martin** [comment]
Thanks, I'll look into it this weekend. I am not using Shortcut anymore so I don't have a good way to test it without opening a new account.

**Comment by omairvaiyani** [comment]
@j-martin Would you like me to help as a maintainer? We use Shortcut as our primary ticket management tool at our [company](https://synap.ac).

**Comment by j-martin** [comment]
@omairvaiyani sure, I invited you to the repo. What is your npm.js account so I can give you publish access?

**Comment by omairvaiyani** [comment]
> @omairvaiyani sure, I invited you to the repo. What is your npm.js account so I can give you publish access?

Thank @j-martin my username is `omairvaiyani`.

Let me know if you prefer to have someone else approve this PR to avoid me merging my own.

**Review by j-martin — APPROVED** [review]
I trust that you tested it. :)

**Comment by j-martin** [comment]
@omairvaiyani I have added you to the npmjs org so you should be able to publish a new version.

**Comment by omairvaiyani** [comment]
> @omairvaiyani I have added you to the npmjs org so you should be able to publish a new version.

Thanks @j-martin though I can only see the deprecated `clubhouse-cli` package, not this one?

**Comment by mdnyhus** [comment]
@omairvaiyani j-martin just made me an admin of this github repo, are you still interested in being a maintainer?

**Comment by acr92** [comment]
Could this PR be fixed, and merged, please? :D

**Comment by omairvaiyani** [comment]
> Could this PR be fixed, and merged, please? :D

I've rebased - ready for merge I hope @mdnyhus

**Comment by mdnyhus** [comment]
Sorry this slipped through the cracks, I'll get a new version out with this change soon.

**Comment by mdnyhus** [comment]
I've released version 2.3.4 that contains this change (and some dependency updates)

**Pull request merged**
